"""
AWS Cost Alert Lambda
----------------------
Queries month-to-date UnblendedCost via Cost Explorer (ce:GetCostAndUsage)
and publishes an SNS alert if spend exceeds a configured threshold.

Environment variables:
    SNS_TOPIC_ARN  - ARN of the SNS topic to publish alerts to (required)
    THRESHOLD      - Dollar threshold to alert above (default: "50")
"""

import os
import json
import datetime
import boto3

# 3.1 Initialize ce and sns clients
ce = boto3.client("ce")
sns = boto3.client("sns")


def _month_to_date_range(today=None):
    """Return (start, end) ISO date strings for the current month so far.

    Cost Explorer requires End to be strictly after Start, so if today is
    the 1st of the month we roll End forward by one day.
    """
    today = today or datetime.date.today()
    start = today.replace(day=1)
    end = today

    if start == end:
        end = start + datetime.timedelta(days=1)

    return start.isoformat(), end.isoformat()


def lambda_handler(event, context):
    threshold = float(os.environ.get("THRESHOLD", "50"))
    topic_arn = os.environ["SNS_TOPIC_ARN"]

    start, end = _month_to_date_range()

    # 3.2 Query month-to-date UnblendedCost
    response = ce.get_cost_and_usage(
        TimePeriod={"Start": start, "End": end},
        Granularity="MONTHLY",
        Metrics=["UnblendedCost"],
    )

    result = response["ResultsByTime"][0]["Total"]["UnblendedCost"]
    amount = float(result["Amount"])
    unit = result["Unit"]

    # 3.5 Print the retrieved amount for logging (always, alert or not)
    print(f"Month-to-date spend: {amount:.2f} {unit} "
          f"(period {start} to {end}, threshold {threshold:.2f})")

    alert_sent = False

    # 3.3 Compare against threshold
    if amount > threshold:
        message = (
            "AWS Cost Alert\n"
            "==============\n\n"
            f"Month-to-date spend: {amount:.2f} {unit}\n"
            f"Threshold:           {threshold:.2f} {unit}\n"
            f"Billing period:      {start} to {end}\n\n"
            "This alert was generated by the ce:GetCostAndUsage Lambda check."
        )

        # 3.4 Publish SNS alert with current spend
        sns.publish(
            TopicArn=topic_arn,
            Subject=f"AWS Cost Alert: ${amount:.2f} exceeds ${threshold:.2f}",
            Message=message,
        )
        alert_sent = True
        print("Threshold exceeded — alert published to SNS.")
    else:
        print("Spend is within threshold — no alert sent.")

    return {
        "statusCode": 200,
        "body": json.dumps({
            "amount": amount,
            "unit": unit,
            "threshold": threshold,
            "period_start": start,
            "period_end": end,
            "alert_sent": alert_sent,
        }),
    }